AarKro/Hera

- .github/CONTRIBUTING.md
Copied guidelines from the Discord channel and added some Github markdown for proper formatting.
[adding this for testing with github projects #53 ]
> #53 Create CONTRIBUTING.md

- .github/CONTRIBUTING.md
Issue: #55 
Small update to the contributing guidelines.
> [#55] Update CONTRIBUTING.md

- .github/CONTRIBUTING.md
Issue: #70 
Updated contributing guidelines to include feature issue handling.
Fixed some typos.
Also made some updates to outdated parts of the guideline that no longer accurately reflect our desired feature / issues management system.
> [#70] Updated contributing guidelines

- metrics/pom.xml
- metrics/src/main/java/hera/metrics/MetricsLogger.java
- pom.xml
Issue: #82 
Added Statistics module, but named it Metrics module because I think it more accurately reflects what the module does.
Added metrics logger.
This module looks kind of overkill right now, since it only contains one class (The metrics logger). But in the future, when we create a Hera API to access these metrics from outside, we will extend this module. So it is good to have for the future
> [#82] Statistics module

- core/src/main/java/hera/core/HeraUtil.java
- core/src/main/java/hera/core/commands/Commands.java
- core/src/main/java/hera/core/commands/Version.java
- data/src/main/java/hera/database/types/CommandName.java
- data/src/main/java/hera/database/types/GlobalSettingKey.java
- data/src/main/java/hera/database/types/LocalisationKey.java
- environment/sql/data.sql
Issue: #99 
Created "version" command similar to the "uptime" structure. Also updated data.sql.
@AarKro @Pacmens
> [#99] Version Command

- core/src/main/java/hera/core/HeraUtil.java
- core/src/main/java/hera/core/commands/Commands.java
- core/src/main/java/hera/core/commands/DeleteMessages.java
- data/src/main/java/hera/database/types/CommandName.java
- environment/sql/data.sql
Issue: #101 
Created command to delete last messages (depending on number given as param).
Delete command message is deleted as well in the end.
@AarKro @Pacmens
> [#101] Delete Messages Command

- core/src/main/java/hera/core/commands/Commands.java
- core/src/main/java/hera/core/commands/Help.java
- core/src/main/java/hera/core/commands/Version.java
- data/src/main/java/hera/database/types/CommandName.java
- data/src/main/java/hera/database/types/LocalisationKey.java
- environment/sql/data.sql
Issue: #100 
Created help command and added references to it in all the needed places as well as updated database statements.
> [#100] Added help command without parameters for now.

- core/src/main/java/hera/core/HeraUtil.java
- core/src/main/java/hera/core/commands/Alias.java
- core/src/main/java/hera/core/commands/Commands.java
- data/src/main/java/hera/database/entities/mapped/Alias.java
- data/src/main/java/hera/database/entities/persistence/AliasPO.java
- data/src/main/java/hera/database/types/CommandName.java
- data/src/main/java/hera/store/DataStore.java
- data/src/main/java/hera/store/unit/AliasAccessUnit.java
- data/src/main/java/hera/store/unit/CommandAccessUnit.java
- environment/sql/constraints.sql
- environment/sql/data.sql
- environment/sql/tables/alias.sql
Added allias functionality 
issues:
#116 
#117 
#118
> [#75] feature/alias

- core/src/main/java/hera/core/commands/Commands.java
- core/src/main/java/hera/core/commands/Prefix.java
- data/src/main/java/hera/database/DAO.java
- data/src/main/java/hera/database/entities/persistence/GuildSettingsPO.java
- data/src/main/java/hera/database/types/CommandName.java
- data/src/main/java/hera/database/types/LocalisationKey.java
- data/src/main/java/hera/store/unit/GuildSettingsAccessUnit.java
- environment/sql/data.sql
Issue: #98 
Implemented prefix command that updates prefix in database and loads it into discord data.
> [#98] Prefix Command

- data/src/main/java/hera/database/JPAUtil.java
- data/src/main/resources/META-INF/persistence.xml
- Set Default Hibernate Dialect to MySQLDialect
- Set Default Timezone to UTC
> Hotfixing Hibernate Windows

- environment/sql/data.sql
> [#131] Added aliases.

- core/src/main/java/hera/core/HeraUtil.java
- core/src/main/java/hera/core/commands/Prefix.java
- core/src/main/java/hera/core/commands/Volume.java
- core/src/main/java/hera/core/music/HeraAudioManager.java
- data/src/main/java/hera/database/entities/mapped/GlobalSetting.java
- data/src/main/java/hera/database/entities/mapped/GuildSetting.java
- data/src/main/java/hera/database/entities/persistence/GlobalSettingPO.java
- data/src/main/java/hera/database/entities/persistence/GuildSettingPO.java
- data/src/main/java/hera/store/unit/GuildSettingAccessUnit.java
> [Release] Last hotfixes

- core/src/main/java/hera/core/HeraUtil.java
- core/src/main/java/hera/core/commands/Prefix.java
- core/src/main/java/hera/core/commands/Volume.java
- core/src/main/java/hera/core/music/HeraAudioManager.java
- data/src/main/java/hera/database/entities/mapped/GlobalSetting.java
- data/src/main/java/hera/database/entities/mapped/GuildSetting.java
- data/src/main/java/hera/database/entities/persistence/GlobalSettingPO.java
- data/src/main/java/hera/database/entities/persistence/GuildSettingPO.java
- data/src/main/java/hera/store/unit/GuildSettingAccessUnit.java
> [Release] Final alpha pre-release hotifx

- core/src/main/java/hera/core/Core.java
- data/src/main/java/hera/database/types/MetricKey.java
- metrics/src/main/java/hera/metrics/MetricsLogger.java
Issue: #142
New metrics:
* User joins voice channel
* User leaves voice channel
* User joins guild
* User leaves guild
* Hera joins guild
> [#142] Added new metrics

- data/src/main/java/hera/database/DAO.java
- data/src/main/java/hera/store/exception/FailedAfterRetriesException.java
- data/src/main/java/hera/store/unit/GuildAccessUnit.java
- data/src/main/java/hera/store/unit/GuildSettingAccessUnit.java
- data/src/main/java/hera/store/unit/MetricAccessUnit.java
- data/src/main/java/hera/store/unit/ModuleSettingsAccessUnit.java
- data/src/main/java/hera/store/unit/StorageAccessUnit.java
> [#143] Added a retry functions and implemented it for all dao calls

- core/src/main/java/hera/core/HeraUtil.java
- core/src/main/java/hera/core/commands/Commands.java
- core/src/main/java/hera/core/commands/ReloadData.java
- data/src/main/java/hera/database/entities/mapped/Command.java
- data/src/main/java/hera/database/entities/persistence/CommandPO.java
- data/src/main/java/hera/database/types/CommandName.java
- data/src/main/java/hera/store/DataStore.java
- environment/sql/data.sql
- environment/sql/tables/command.sql
Reload data command added. Changed admin to level in command table.
> [#166] reload data command

- core/src/main/java/hera/core/commands/Flip.java
- core/src/main/java/hera/core/commands/Teams.java
changed imports in flip and teams
> [hotfix] imports

- core/src/main/java/hera/core/HeraUtil.java
- core/src/main/java/hera/core/commands/Alias.java
- core/src/main/java/hera/core/commands/Clear.java
- core/src/main/java/hera/core/commands/DeleteMessages.java
- core/src/main/java/hera/core/commands/Flip.java
- core/src/main/java/hera/core/commands/JumpTo.java
- core/src/main/java/hera/core/commands/LoopQueue.java
- core/src/main/java/hera/core/commands/Move.java
- core/src/main/java/hera/core/commands/NowPlaying.java
- core/src/main/java/hera/core/commands/OnJoinRole.java
- core/src/main/java/hera/core/commands/Pause.java
- core/src/main/java/hera/core/commands/Prefix.java
- core/src/main/java/hera/core/commands/Queue.java
- core/src/main/java/hera/core/commands/Remove.java
- core/src/main/java/hera/core/commands/Resume.java
- core/src/main/java/hera/core/commands/Shuffle.java
- core/src/main/java/hera/core/commands/Teams.java
- core/src/main/java/hera/core/commands/ToggleCommand.java
- core/src/main/java/hera/core/commands/UpdateYtToken.java
- core/src/main/java/hera/core/commands/Uptime.java
- core/src/main/java/hera/core/commands/Version.java
- core/src/main/java/hera/core/commands/Volume.java
- core/src/main/java/hera/core/messages/HeraMsgSpec.java
- core/src/main/java/hera/core/messages/MessageSender.java
- core/src/main/java/hera/core/messages/MessageType.java
- core/src/main/java/hera/core/music/HeraAudioLoadResultHandler.java
Issue: #185 
Added new MessageSender class. All actions that want to send a message to a discord message channel should use `MessageSender.send()`.
Refactored all existing code to use the MessageSender class.
Feel free to change `MessageType` or anything if it doesn't fit the actual message that is sent.
> [#185] Added MessageSender class and refactored application to use it

- core/pom.xml
- core/src/main/java/hera/core/commands/Help.java
- data/pom.xml
- metrics/pom.xml
- pom.xml
changed help message to default type. updated version
> [RELEASE] 2.0.0-alpha.3

- LICENSE
> [#184] Create LICENSE

- docs/index.html
Added this now so I can reference it in the README.MD
> [No Ticket] Added /docs folder for future website on Github Pages

- README.md
Finally got around to update the README.
Added a quick description of Hera at the beginning (the same we have on Discord).
Added setup and deployment instructions for the chatbot, website & API.
Please spell check and make sure what I wrote makes sense.
> [No Ticket] Update README with development setup instructions

- data/pom.xml
- data/src/main/java/hera/database/entities/ModuleSettings.kt
- data/src/main/resources/META-INF/persistence.xml
Added c3p0 dependency and properties to the project.
Also hotfixed a database missmatch in the modul settings table. A column that was named enabled in the databse was maped to isEnabled in the project. How it worked so far no idea magic i guess.
> [#203] Add c3p0

- data/pom.xml
- data/src/main/java/hera/database/entities/ModuleSettings.kt
- data/src/main/resources/META-INF/persistence.xml
Added c3p0 config to the project and fixed a db missmatch (isEnabled in entity enabled in db). (#218)
> [Hotfix] Fixing database connection

- core/pom.xml
Also update lavaplayer to 1.3.50
> [No Ticket] Update Discord4J version to 3.0.15

- api/pom.xml
- api/src/main/kotlin/hera/api/ApiApplication.kt
- api/src/main/kotlin/hera/api/schemas/Test.kt
- api/src/main/resources/application.properties
- appspec.yml
- buildspec.yml
- data/pom.xml
- pom.xml
> [#239] Base Structure for Hera API

- api/pom.xml
- core/pom.xml
- data/pom.xml
- environment/sql/data.sql
- metrics/pom.xml
- pom.xml
fast beta1 release to finally fix music
> [RELEASE] beta 1

- environment/scripts/create_demployment_sql.sh
- environment/scripts/setup_db.sh
- environment/sql/templates/general_info.txt
- environment/sql/templates/new_command_templ.sql
Changed scripts to use the updates folder and added template for new commands
> [#248] make database setup modular

- environment/scripts/setup_db.sh
Made setup_db.sh actually possibly work.
> [HOTFIX] update database modularity

- core/pom.xml
- core/src/main/java/hera/core/Core.java
- core/src/main/java/hera/core/api/handlers/YouTubeApiHandler.java
- core/src/main/java/hera/core/commands/miscellaneous/Vote.java
- core/src/main/java/hera/core/messages/MessageHandler.java
Addded all intents back to the scope which should fix the onjoinrole
> fixed onjoinrole, updated dependencies

- core/src/main/java/hera/core/Core.java
> [HOTFIX] onjoinrole fix
